collective_synonyms = {
    'agricultores': ['agricultores', 'campesinos', 'cultivadores', 'trabajadores agrícolas', 'trabajadores del sector agrícola', 'trabajadores rurales', 'ganaderos', 'regantes', 'apicultores', 'viticultores', 'fruticultores', 'pastores', 'pequeños productores', 'productores', 'productores locales', 'productores agroalimentarios'],
    'artistas': ['artistas', 'actores', 'actrices', 'músicos', 'cantantes', 'compositores', 'cineastas', 'fotógrafos', 'diseñadores', 'modelos', 'bailarines', 'escritores', 'poetas', 'autores'],
    'autoridades': ['autoridades', 'autoridades locales', 'autoridades municipales', 'autoridades judiciales', 'autoridades civiles', 'gobierno', 'gobiernos', 'gobierno municipal', 'gobierno local', 'gobiernos locales', 'gobiernos autonómicos', 'administraciones', 'administraciones públicas', 'administraciones locales', 'ayuntamiento', 'ayuntamientos', 'corporaciones locales', 'administradores', 'líderes secesionistas', 'líderes independentistas', 'líderes europeos', 'jefes de estado y de gobierno', 'cargos públicos', 'políticos', 'políticos locales', 'diputados', 'senadores', 'parlamentarios', 'ministros', 'alcaldes', 'funcionarios', 'magistrados', 'fiscales', 'agentes locales', 'agentes medioambientales', 'agentes de seguridad', 'agentes de la ley', 'agentes', 'autoridades políticas'],
    'cuerpos_de_seguridad': ['cuerpos de seguridad', 'fuerzas de seguridad', 'fuerzas y cuerpos de seguridad del estado', 'guardia civil', 'guardias civiles', 'policías', 'policía', 'policía nacional', 'policías nacionales', 'funcionarios policiales', 'cuerpos de seguridad del estado', 'militares', 'soldados', 'fuerzas armadas','suboficiales'],
    'deportistas': ['deportistas', 'atletas', 'deportistas con discapacidad', 'paralímpicos', 'deportistas femeninas', 'futbolistas', 'jugadores de fútbol', 'jugadoras de fútbol', 'atletas olímpicos', 'olímpicos', 'jugadores de baloncesto', 'baloncestistas', 'nadadores', 'escaladores', 'esquiadores', 'corredores', 'boxeadores', 'púgiles', 'jugadores de tenis', 'tenistas', 'jugadores de ajedrez', 'jugadores sub-23', 'equipos de fútbol', 'equipos deportivos', 'jugadoras', 'jugadores'],
    'estudiantes': ['estudiantes', 'estudiantes universitarios', 'universitarios', 'estudiantes de medicina', 'alumnos', 'alumnado', 'alumnos de primaria', 'alumnos y alumnas', 'escolares'],
    'familias': ['familias', 'familia', 'familia real', 'familia real británica', 'clan familiar', 'clanes familiares'],
    'migrantes': ['inmigrantes', 'migrantes', 'emigrantes', 'emigrantes retornados', 'inmigrantes ilegales', 'migrantes irregulares', 'personas migrantes', 'migrantes menores', 'menores migrantes', 'menores inmigrantes no acompañados', 'menores no acompañados', 'menores extranjeros no acompañados'],
    'refugiados': ['refugiados', 'refugiados palestinos', 'refugiados saharauis', 'solicitantes de asilo', 'personas desplazadas', 'desplazados'],
    'jóvenes': ['jóvenes', 'juventud', 'adolescentes', 'jóvenes músicos', 'jóvenes instrumentistas', 'jóvenes tutelados', 'jóvenes agricultores', 'jóvenes emprendedores', 'generación z', 'nuevas generaciones'],
    'mujeres': ['mujeres', 'mujeres jóvenes', 'mujeres embarazadas', 'mujeres deportistas', 'mujeres rurales', 'mujeres iraníes', 'mujeres de la nobleza', 'mujeres empresarias', 'embarazadas', 'madres'],
    'niños': ['niños', 'niñas', 'infancia', 'menores', 'niños y niñas', 'niños y adolescentes', 'infancia y juventud', 'población infantil', 'niños saharauis', 'menores de edad'],
    'personas_con_discapacidad': ['personas con discapacidad', 'personas con discapacidades', 'personas con discapacidad intelectual', 'personas con movilidad reducida', 'personas con parálisis cerebral', 'personas con lesiones cerebrales', 'personas con síndrome de down', 'discapacitados', 'personas con discapacidad visual', 'personas con enfermedades raras', 'personas con alzheimer', 'personas con ela', 'enfermos de esclerosis lateral amiotrófica', 'pacientes con insuficiencia cardíaca', 'pacientes dermatológicos', 'pacientes con enfermedades crónicas', 'pacientes con cáncer', 'pacientes oncológicos', 'personas con diabetes', 'personas con obesidad', 'personas con adicciones', 'personas con sobrepeso'],
    'personas_mayores': ['personas mayores', 'mayores', 'adultos mayores', 'mayores de 60 años', 'mayores de 65 años', 'gente mayor', 'mayores de 75 años', 'población envejecida', 'jubilados', 'pensionistas'],
    'profesionales_de_la_salud': ['profesionales de la salud', 'profesionales sanitarios', 'sanitarios', 'personal sanitario', 'profesionales médicos', 'médicos', 'médicos de familia', 'personal médico', 'enfermeros', 'enfermeras', 'profesionales de enfermería', 'trabajadores de la salud', 'farmacéuticos', 'personal de emergencia'],
    'trabajadores': ['trabajadores', 'trabajadores municipales', 'trabajadores del ayuntamiento', 'trabajadores de prisiones', 'trabajadores de la construcción', 'trabajadores interinos', 'trabajadores desempleados', 'empleados', 'asalariados', 'obreros', 'operarios', 'autónomos', 'trabajadores autónomos', 'trabajadoras'],
    'vecinos': ['vecinos', 'residentes', 'habitantes', 'vecinos afectados', 'habitantes locales', 'residentes locales', 'habitantes de león', 'residentes de león', 'vecinos de ponferrada', 'población local', 'poblaciones locales', 'comunidad local', 'comunidades locales', 'habitantes del bierzo', 'habitantes de laciana', 'habitantes de municipios pequeños'],
    'personas_vulnerables': ['personas vulnerables', 'personas desfavorecidas', 'personas en riesgo de exclusión social', 'personas en situación de vulnerabilidad', 'personas necesitadas', 'personas en riesgo de pobreza', 'grupos vulnerables', 'colectivos vulnerables', 'hogares vulnerables', 'comunidades vulnerables', 'vulnerables'],
    'personas_sin_hogar': ['personas sin hogar', 'personas sin techo', 'sin techo', 'personas en situación de calle'],
    'lgtbi': ['lgtbi', 'lgtbi+', 'colectivo lgtbi', 'personas lgtbi', 'personas trans', 'comunidad lgtbiq+'],
    'población_rural': ['población rural', 'poblaciones rurales', 'habitantes de zonas rurales', 'zonas rurales', 'comunidades rurales', 'pueblos', 'aldeanos', 'españa vaciada'],
    'personas_con_enfermedades': ['personas con enfermedades', 'personas con enfermedades raras', 'personas con condiciones de salud', 'personas con condiciones de salud mental', 'personas con enfermedades mentales', 'personas con adicciones', 'personas con diabetes', 'personas con obesidad', 'personas con sobrepeso', 'personas con cáncer', 'personas con alzheimer', 'personas con ela', 'enfermos de esclerosis lateral amiotrófica', 'pacientes con insuficiencia cardíaca', 'pacientes dermatológicos', 'pacientes con enfermedades crónicas', 'pacientes con cáncer', 'pacientes oncológicos'],
    'empleados': ['empleados', 'empleados municipales'],
    'personas_con_discapacidad_visual': ['personas con discapacidad visual', 'personas ciegas', 'invidentes'],
    'aficionados': ['aficionados', 'afición', 'aficionados a la música', 'aficionados a la pesca', 'aficionados al ajedrez', 'aficionados a la astronomía', 'aficionados taurinos', 'fanáticos', 'fans', 'seguidores'],
    'animales': ['animales', 'animales de compañía'],
    'defensores_de_derechos_humanos': ['defensores de derechos humanos', 'activistas', 'protectores de animales'],
    'científicos': ['científicos', 'investigadores', 'arqueólogos', 'historiadores', 'antropólogos', 'biólogos', 'geólogos', 'astrónomos', 'astronautas', 'historiadores del arte', 'analistas', 'analistas militares', 'expertos', 'especialistas', 'técnicos'],
    'criminales': ['criminales', 'delincuentes', 'ladrones', 'traficantes', 'narcotraficantes', 'ciberdelincuentes', 'estafadores', 'infractores', 'menores infractores'],
    'clientes_consumidores': ['clientes', 'consumidores', 'consumidores de drogas', 'consumidores de cerveza sin alcohol', 'público', 'público general', 'público infantil', 'público familiar', 'espectadores', 'comensales', 'viandantes', 'transeúntes', 'usuarios', 'usuarios de redes sociales', 'usuarios de trenes', 'usuarios de tren', 'usuarios de transporte', 'usuarios de piscinas', 'usuarios de autopistas', 'usuarios de transporte público'],
    'minorías_étnicas': ['minorías étnicas', 'afroamericanos', 'gitanos', 'indígenas', 'pueblo gitano', 'mujeres gitanas'],
    'voluntarios': ['voluntarios', 'asistentes'],
    'votantes': ['votantes', 'electores'],
    'pescadores': ['pescadores', 'aficionados a la pesca'],
    'ecologistas': ['ecologistas', 'conservacionistas', 'protectores de animales', 'animalistas'],
    'profesionales': ['profesionales', 'profesionales tecnológicos', 'profesionales médicos', 'profesionales de la salud', 'profesionales sanitarios', 'profesionales del sector', 'profesionales de enfermería'],
    'personas_en_riesgo_de_exclusión_social': ['personas en riesgo de exclusión social', 'personas desfavorecidas', 'personas necesitadas', 'personas en riesgo de pobreza', 'personas vulnerables', 'grupos vulnerables', 'colectivos vulnerables', 'familias vulnerables', 'hogares vulnerables', 'comunidades vulnerables', 'vulnerables'],
    'bomberos': ['bomberos'],
    'empresas': ['empresas', 'empresas tecnológicas', 'empresas agroalimentarias', 'pymes', 'microempresas', 'multinacionales', 'negocios', 'startups', 'pequeñas empresas', 'pequeñas y medianas empresas', 'patronal', 'sector primario'],
    'funcionarios': ['funcionarios', 'funcionarios públicos', 'funcionarios municipales', 'funcionarios judiciales', 'funcionarios penitenciarios', 'funcionarios policiales', 'empleados públicos'],
    'veterinarios': ['veterinarios'],
    'turistas': ['turistas', 'visitantes', 'viajeros', 'peregrinos'],
    'conductores': ['conductores', 'automovilistas', 'camioneros', 'pilotos', 'pilotos de fórmula 1', 'maquinistas', 'motociclistas', 'motoristas', 'moteros', 'ciclistas', 'usuarios de trenes'],
    'clientes': ['clientes', 'consumidores'],
    'personas_sin_hogar': ['personas sin hogar', 'personas sin techo', 'sin techo', 'personas en situación de calle', 'drogodependientes', 'personas con adicciones', 'alcohólicos rehabilitados'],
    'veteranos': ['veteranos', 'ex mineros', 'reservistas'],
    'artesanos': ['artesanos', 'artistas', 'artistas locales', 'artistas callejeros', 'artistas flamencos', 'artistas circenses', 'bailarines', 'escritores', 'poetas', 'autores', 'autores leoneses', 'creadores', 'creadores de contenido', 'diseñadores', 'diseñadores de moda', 'modelos', 'fotógrafos', 'artistas urbanos'],
    'personas_con_adicciones': ['personas con adicciones', 'drogodependientes', 'alcohólicos rehabilitados'],
    'directivos': ['directivos', 'ejecutivos', 'directores', 'directivos del club', 'altos cargos', 'administradores'],
    'periodistas': ['periodistas', 'medios de comunicación', 'editores'],
    'emprendedores': ['emprendedores', 'empresarios', 'pequeños empresarios', 'mujeres empresarias', 'jóvenes emprendedores'],
    'ciclistas': ['ciclistas', 'escaladores', 'senderistas', 'montañeros', 'esquiadores'],
    'propietarios': ['propietarios', 'propietarios afectados', 'propietarios de perros', 'propietarios de viviendas', 'propietarios privados', 'dueños de mascotas'],
    'personas_con_cáncer': ['personas con cáncer', 'pacientes con cáncer', 'pacientes de cáncer', 'pacientes oncológicos', 'enfermos de cáncer', 'supervivientes de cáncer', 'niños y adolescentes enfermos de cáncer', 'mujeres con cáncer de mama'],
    'opositores_políticos': ['opositores políticos', 'opositores', 'opositores venezolanos', 'oposición', 'oposición venezolana', 'antifascistas', 'resistencia'],
    'trabajadores_sexuales': ['trabajadores sexuales'],
    'religiosos': ['religiosos', 'religiosas', 'clérigos', 'clero', 'sacerdotes', 'monjes', 'monjas', 'eclesiásticos', 'católicos', 'creyentes', 'fieles', 'devotos', 'cristianos'],
    'víctimas': ['víctimas', 'víctimas de abuso', 'víctimas de abusos', 'víctimas de abuso sexual', 'víctimas de violencia', 'víctimas de violencia doméstica', 'víctimas de violencia de género', 'víctimas de violencia sexual', 'víctimas del terrorismo', 'víctimas de la guerra civil', 'heridos', 'damnificados', 'represaliados', 'personas afectadas'],
    'sociedad_civil': ['sociedad civil', 'comunidad', 'comunidades', 'comunidad local', 'comunidades locales', 'comunidad internacional', 'comunidades autónomas', 'comunidades de vecinos', 'sociedad', 'pueblo de león', 'pueblo venezolano', 'pueblo gitano', 'pueblo palestino'],
    'animalistas': ['animalistas', 'protectores de animales', 'defensores de derechos humanos', 'ecologistas', 'conservacionistas'],
    'usuarios_de_transporte': ['usuarios de trenes', 'usuarios de tren', 'usuarios de transporte', 'usuarios de transporte público', 'pasajeros', 'viajeros'],
    'maestros': ['maestros', 'profesores', 'docentes', 'educadores', 'profesorado', 'profesores universitarios', 'catedráticos', 'tutores'],
    'abogados': ['abogados', 'juristas'],
    'aficionados_a_la_música': ['aficionados a la música', 'melómanos', 'amantes del cine'],
    'personas_con_enfermedades_mentales': ['personas con enfermedades mentales', 'personas con condiciones de salud mental', 'personas sensibles'],
    'jueces': ['jueces', 'magistrados', 'autoridades judiciales', 'fiscales', 'fiscalía'],
    'familiares': ['familiares', 'familiares de víctimas', 'familiares de la víctima', 'familias de pacientes', 'madres y padres de alumnos', 'padres', 'madres', 'padres y madres'],
    'españoles': ['españoles', 'ciudadanos españoles'],
    'desempleados': ['desempleados', 'trabajadores desempleados', 'parados de larga duración', 'personas desempleadas', 'parados'],
    'profesionales_tecnológicos': ['profesionales tecnológicos', 'informáticos', 'ingenieros', 'arquitectos', 'diseñadores', 'diseñadores de moda', 'gestores culturales', 'startups'],
    'personas_con_ela': ['personas con ela', 'pacientes con ela', 'afectados por ela', 'enfermos de esclerosis lateral amiotrófica'],
    'personas_con_diabetes': ['personas con diabetes'],
    'personas_con_alzheimer': ['personas con alzhéimer', 'personas con alzheimer', 'pacientes con alzhéimer'],
    'personas_con_obesidad': ['personas con obesidad', 'personas con sobrepeso'],
    'pacientes_con_insuficiencia_cardiaca': ['pacientes con insuficiencia cardíaca'],
    'personal_de_emergencia': ['personal de emergencia', 'bomberos', 'sanitarios', 'profesionales de la salud'],
    'temporeros': ['temporeros'],
    'profesores_universitarios': ['profesores universitarios', 'catedráticos', 'docentes', 'profesorado'],
    'universidades': ['universidades', 'universidades públicas', 'comunidad universitaria'],
    'militares_ucranianos': ['tropas ucranianas', 'fuerzas ucranianas', 'soldados ucranianos', 'militares'],
    'opositores': ['opositores', 'opositores políticos', 'opositores venezolanos', 'oposición', 'oposición venezolana'],
    'menores_infractores': ['menores infractores', 'infractores', 'delincuentes juveniles'],
    'administraciones_públicas': ['administraciones públicas', 'administraciones locales', 'gobiernos locales', 'gobiernos autonómicos', 'gobierno municipal', 'gobierno local', 'ayuntamiento', 'ayuntamientos'],
    'vendedores': ['vendedores', 'comerciantes', 'expositores', 'negocios'],
    'usuarios_de_redes_sociales': ['usuarios de redes sociales', 'influencers', 'creadores de contenido', 'seguidores'],
    'personas_con_enfermedades_crónicas': ['personas con enfermedades crónicas', 'pacientes con enfermedades crónicas'],
    'pacientes_pediátricos': ['pacientes pediátricos', 'niños', 'pediátricos'],
    'profesionales_deportivos': ['profesionales deportivos', 'deportistas', 'entrenadores', 'jugadores', 'jugadoras', 'clubes deportivos', 'equipos deportivos'],
    'políticos': ['partidos políticos', 'cargos públicos', 'políticos', 'políticos locales', 'militantes', 'simpatizantes', 'afiliados'],
    'personas_con_lesiones_cerebrales': ['personas con lesiones cerebrales', 'personas con parálisis cerebral', 'personas con discapacidad intelectual'],
    'clase_media': ['clase media', 'clases medias', 'clases medias acomodadas'],
    'personas_en_riesgo_de_pobreza': ['personas en riesgo de pobreza', 'personas en riesgo de exclusión social'],
    'cofradías': ['cofradías', 'hermanos de cofradía', 'cofrades', 'cofradía'],
    'gobernantes': ['gobernantes', 'dirigentes', 'dirigentes políticos', 'líderes políticos', 'líderes mundiales', 'autoridades políticas'],
    'trabajadores_del_ayuntamiento': ['trabajadores del ayuntamiento', 'empleados municipales', 'funcionarios municipales'],
    'población': ['población', 'sociedad', 'ciudadanía', 'público general', 'habitantes'],
    'tripulantes': ['tripulantes', 'personal de vuelo', 'marineros'],
    'damnificados': ['damnificados', 'afectados', 'personas afectadas'],
    'profesionales_del_sector': ['profesionales del sector', 'trabajadores', 'empleados', 'asalariados'],
    'senadores': ['senadores', 'diputados', 'parlamentarios', 'eurodiputados'],
    'personas_sensibles': ['personas sensibles', 'personas con enfermedades mentales', 'personas con condiciones de salud mental'],
    'grupos_de_riesgo': ['grupos de riesgo', 'personas vulnerables', 'colectivos vulnerables'],
    'familia_real': ['familia real', 'familia real británica', 'miembros de la realeza'],
    'combatientes': ['combatientes', 'guerrilleros', 'milicianos', 'milicianos palestinos'],
    'supervivientes': ['supervivientes', 'víctimas', 'personas afectadas'],
    'pasajeros': ['pasajeros', 'usuarios de transporte', 'viajeros'],
    'pilotos': ['pilotos', 'pilotos de fórmula 1', 'aviadores'],
    'niños_con_necesidades_especiales': ['niños con necesidades especiales', 'niños con discapacidades', 'niños con enfermedades raras'],
    'vulnerables': ['vulnerables', 'personas vulnerables', 'grupos vulnerables', 'personas desfavorecidas'],
    'población_envejecida': ['población envejecida', 'personas mayores', 'mayores', 'ancianos', 'adultos mayores'],
    'manifestantes': ['manifestantes', 'protestantes', 'activistas'],
    'diplomáticos': ['diplomáticos', 'embajadores', 'representantes'],
    'terroristas': ['terroristas', 'extremistas', 'radicales'],
    'nómadas_digitales': ['nómadas digitales', 'trabajadores remotos', 'freelancers'],
    'extranjeros': ['extranjeros', 'foráneos'],
    'sectores_en_desarrollo': ['países en desarrollo', 'comunidades en desarrollo'],
    'población_infantil': ['población infantil', 'niños', 'infancia', 'infancia y juventud'],
    'rehenes': ['rehenes', 'secuestrados'],
    'personas_sordas': ['personas sordas', 'personas con discapacidad auditiva'],
    'personas_con_síndrome_de_down': ['personas con síndrome de down'],
    'empleados_públicos': ['empleados públicos', 'funcionarios', 'trabajadores del sector público'],
    'personas_con_cáncer': ['personas con cáncer', 'pacientes con cáncer', 'enfermos de cáncer'],
    'comunidad_educativa': ['comunidad educativa', 'estudiantes', 'profesores', 'padres y madres'],
    'personas_con_movilidad_reducida': ['personas con movilidad reducida', 'personas con discapacidad motriz'],
    'líderes_europeos': ['líderes europeos', 'gobernantes', 'dirigentes'],
    'fuerzas_ucranianas': ['fuerzas ucranianas', 'tropas ucranianas', 'soldados ucranianos'],
    'personas_sin_techo': ['personas sin techo', 'personas sin hogar', 'personas en situación de calle'],
    'niños_y_adolescentes': ['niños y adolescentes', 'niños', 'adolescentes', 'infancia y juventud'],
    'pymes': ['pymes', 'pequeñas y medianas empresas', 'pequeñas empresas', 'microempresas'],
    'autónomos': ['autónomos', 'trabajadores autónomos', 'emprendedores'],
    'beneficiarios': ['beneficiarios', 'receptores', 'donatarios'],
    'donantes': ['donantes', 'colaboradores', 'patrocinadores'],
    'gobiernos_locales': ['gobiernos locales', 'administraciones locales', 'ayuntamientos'],
    'personas_con_enfermedades_raras': ['personas con enfermedades raras', 'pacientes con enfermedades raras'],
    'pequeños_productores': ['pequeños productores', 'productores locales', 'productores agroalimentarios'],
    'empresas_agroalimentarias': ['empresas agroalimentarias', 'bodegueros'],
    'parlamentarios': ['parlamentarios', 'diputados', 'senadores', 'eurodiputados'],
    'amantes_del_cine': ['amantes del cine', 'cinéfilos'],
    'clubes_deportivos': ['clubes deportivos', 'equipos deportivos', 'clubes', 'equipos de fútbol'],
    'familias_monoparentales': ['familias monoparentales'],
    'pensionistas': ['pensionistas', 'jubilados'],
    'personas_con_discapacidad_visual': ['personas con discapacidad visual', 'invidentes'],
    'narcotraficantes': ['narcotraficantes', 'traficantes de drogas'],
    'eclesiásticos': ['eclesiásticos', 'clero', 'sacerdotes', 'religiosos'],
    'mujeres_con_discapacidad': ['mujeres con discapacidad', 'niñas con discapacidad'],
    'colonos': ['colonos', 'pobladores'],
    'traficantes': ['traficantes', 'narcotraficantes', 'traficantes de drogas'],
    'empresas_tecnológicas': ['empresas tecnológicas', 'startups', 'profesionales tecnológicos'],
    'afectados_por_ela': ['afectados por ela', 'personas con ela'],
    'autoridades_judiciales': ['autoridades judiciales', 'jueces', 'magistrados', 'fiscales'],
    'personas_con_alzheimer': ['personas con alzhéimer', 'pacientes con alzhéimer'],
    'personas_con_síndrome_de_down': ['personas con síndrome de down'],
    'especialistas': ['especialistas', 'expertos', 'técnicos'],
    'palestina': ['civiles palestinos', 'palestinos', 'población civil', 'palestina'],

}



